# Setup
locale: "ko"
timeZone: Asia/Seoul
title: Geunwon of universe
description: 개발 공부 블로그
url: https://MAGEUNWON.github.io
repository: "MAGEUNWON/MAGEUNWON.github.io"
search: true
avatar: /IMG_2594.jpg
permalink: pretty
# permalink: /:categories/:title/
paginate: 5
cover_image: /frog.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: geunwon
  links:
    - https://github.com/MAGEUNWON
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

comments:
  provider: "disqus"
  disqus:
    shortname: dev-hundred-blog

defaults:
  #_posts
  -scope:
    path: ""
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: true #댓글 활성화
    share: true
    related: true

  #_pages
  -scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: true #댓글 활성화
    share: true
    related: true

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: geunwon
  url: https://github.com/MAGEUNWON
  location: "Seoul,Korea"
  email: geunwon1947@gmail.com
  github: "MAGEUNWON"


#Archives
category_archive:
  type: liquid
  path: /categories/