# Setup
locale: "ko"
title: Universe of geunwon
description: 개발 공부 블로그
url: https://MAGEUNWON.github.io
repository: "MAGEUNWON/MAGEUNWON.github.io"
search : true
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: geunwon
  links:
    - https://twitter.com/vszhub
    - https://github.com/MAGEUNWON
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: geunwon
  url: https://github.com/vszhub/
  location: "Seoul,Korea"
  # email: vszhub@gmail.com
  github : "MAGEUNWON"
